# The name of the site will be used to reference theme files.
NAME: "drupal-8-theme"

# Your project's server will run on localhost:xxxx at this port
PORT: 3000

# Folder to clean up before running scripts.
CLEAN:
  - "css"

# Environments
ENVIRONMENTS:
  development: "drupal-8.dd:8083"
  staging: "drupal-8.dd:8083"
  production: "drupal-8.dd:8083"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 8"

# Gulp will reference these paths when it copies files
PATHS:
  themesRoot: "/themes/custom/"
  jsRoot: "/src/scripts/"
  cssRoot: "/css/"
  sassRoot: "/src/sass/"
  images: "/src/images/"
  sass:
    - "src/sass/drupal-8-theme.style.scss"
    - "fonts"